name: cryo-modelling-env-gpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - nodejs
  - ipython
  - jupyterlab
  - jupyterlab-git
  - jsonschema-with-format-nongpl
  - pandas
  - joblib
  - pydot
  - graphviz
  - scikit-learn
  - matplotlib
  - seaborn
  - reportlab
  - svglib
  - cairosvg
  - pymupdf
  - webcolors
  - widgetsnbextension==3.6.0
  - pip
  - pip:
      - tensorflow[and-cuda]==2.20.0
      - tensorflow-datasets==4.8.3
      - keras-tuner
    # Validation notebooks also depend on the external design and Ansys stack.
    # These packages are not pinned here because they often require external desktop software.
    # Add those separately if you plan to run the validation notebooks.
